# trainer_config
import json
import os

DEVICE = "cuda"
cuda = True

coeff = {"ParametersDouble0|X_HC_PostBiquad0Coeffb0": [1., 0.6507, 0.4531, 0.3208, 0.2222, 0.1432, 0.1090, 0.0777],
         "ParametersDouble0|X_HC_PreBiquad0Coeffa1": [0., 1.2664, 1.4010, 1.5411, 1.6873, 1.7781, 1.8401, 1.8968,
                                                      1.9191]}

coeff_post_values = [
    (0., 0., 1., 0., 0.),
    (-1.25, -0.3529, 0.6507, 1.3014, 0.6507),
    (-0.7507, -0.0616, 0.4531, 0.9062, 0.4531),
    (-0.3552, 0.0719, 0.3208, 0.6417, 0.3208),
    (0, -0.1111, 0.2222, 0.4444, 0.2222),
    (0.3552, 0.0719, 0.1432, 0.2865, 0.1432),
    (0.5449, -0.0193, 0.1090, 0.2179, 0.1090),
    (0.7507, -0.0616, 0.0777, 0.1554, 0.0777),
]

coeff_pre_values = [
    (0., 0., 1., 0., 0.),
    (1.2664, -0.4359, 0.6756, -1.3511, 0.6756),
    (1.4010, -0.5164, 0.7293, -1.4587, 0.7293),
    (1.5411, -0.6104, 0.7879, -1.5758, 0.7879),
    (1.6873, -0.7203, 0.8519, -1.7038, 0.8519),
    (1.7781, -0.7950, 0.8933, -1.7866, 0.8933),
    (1.8401, -0.8490, 0.9223, -1.8445, 0.9223),
    (1.8968, -0.9006, 0.9493, -1.8987, 0.9493),
    (1.9191, -0.9214, 0.9601, -1.9202, 0.9601),
]

# with open("./fitting_v1_e7111v2_all_keys.json", "r") as f:
#     all_keys = json.load(f)
# print(len(all_keys))
e7111v2_all_keys = {"OTHERS": ["ParametersDouble0|X_AuxiliaryAttenuation", "ParametersDouble0|X_MicrophoneAttenuation",
                       "ParametersLong0|X_AuxiliaryInput", "ParametersLong0|X_LIM_TargetGain_dB"],
            "X_AuxiliaryAttenuation": ["ParametersDouble0|X_AuxiliaryAttenuation"],
            "X_HC": ["ParametersDouble0|X_HC_PostBiquad0Coeffa1", "ParametersDouble0|X_HC_PostBiquad0Coeffa2",
                     "ParametersDouble0|X_HC_PostBiquad0Coeffb0", "ParametersDouble0|X_HC_PostBiquad0Coeffb1",
                     "ParametersDouble0|X_HC_PostBiquad0Coeffb2", "ParametersDouble0|X_HC_PostBiquad1Coeffa1",
                     "ParametersDouble0|X_HC_PostBiquad1Coeffa2", "ParametersDouble0|X_HC_PostBiquad1Coeffb0",
                     "ParametersDouble0|X_HC_PostBiquad1Coeffb1", "ParametersDouble0|X_HC_PostBiquad1Coeffb2",
                     "ParametersDouble0|X_HC_PostBiquad2Coeffa1", "ParametersDouble0|X_HC_PostBiquad2Coeffa2",
                     "ParametersDouble0|X_HC_PostBiquad2Coeffb0", "ParametersDouble0|X_HC_PostBiquad2Coeffb1",
                     "ParametersDouble0|X_HC_PostBiquad2Coeffb2", "ParametersDouble0|X_HC_PostBiquad3Coeffa1",
                     "ParametersDouble0|X_HC_PostBiquad3Coeffa2", "ParametersDouble0|X_HC_PostBiquad3Coeffb0",
                     "ParametersDouble0|X_HC_PostBiquad3Coeffb1", "ParametersDouble0|X_HC_PostBiquad3Coeffb2",
                     "ParametersDouble0|X_HC_PreBiquad0Coeffa1", "ParametersDouble0|X_HC_PreBiquad0Coeffa2",
                     "ParametersDouble0|X_HC_PreBiquad0Coeffb0", "ParametersDouble0|X_HC_PreBiquad0Coeffb1",
                     "ParametersDouble0|X_HC_PreBiquad0Coeffb2", "ParametersDouble0|X_HC_PreBiquad1Coeffa1",
                     "ParametersDouble0|X_HC_PreBiquad1Coeffa2", "ParametersDouble0|X_HC_PreBiquad1Coeffb0",
                     "ParametersDouble0|X_HC_PreBiquad1Coeffb1", "ParametersDouble0|X_HC_PreBiquad1Coeffb2",
                     "ParametersDouble0|X_HC_PreBiquad2Coeffa1", "ParametersDouble0|X_HC_PreBiquad2Coeffa2",
                     "ParametersDouble0|X_HC_PreBiquad2Coeffb0", "ParametersDouble0|X_HC_PreBiquad2Coeffb1",
                     "ParametersDouble0|X_HC_PreBiquad2Coeffb2", "ParametersDouble0|X_HC_PreBiquad3Coeffa1",
                     "ParametersDouble0|X_HC_PreBiquad3Coeffa2", "ParametersDouble0|X_HC_PreBiquad3Coeffb0",
                     "ParametersDouble0|X_HC_PreBiquad3Coeffb1", "ParametersDouble0|X_HC_PreBiquad3Coeffb2"],
            "X_MicrophoneAttenuation": ["ParametersDouble0|X_MicrophoneAttenuation"],
            "X_AuxiliaryInput": ["ParametersLong0|X_AuxiliaryInput"],
            "X_EQ": ["ParametersLong0|X_EQ_ChannelGain_dB[0]", "ParametersLong0|X_EQ_ChannelGain_dB[1]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[2]", "ParametersLong0|X_EQ_ChannelGain_dB[3]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[4]", "ParametersLong0|X_EQ_ChannelGain_dB[5]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[6]", "ParametersLong0|X_EQ_ChannelGain_dB[7]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[8]", "ParametersLong0|X_EQ_ChannelGain_dB[9]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[10]", "ParametersLong0|X_EQ_ChannelGain_dB[11]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[12]", "ParametersLong0|X_EQ_ChannelGain_dB[13]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[14]", "ParametersLong0|X_EQ_ChannelGain_dB[15]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[16]", "ParametersLong0|X_EQ_ChannelGain_dB[17]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[18]", "ParametersLong0|X_EQ_ChannelGain_dB[19]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[20]", "ParametersLong0|X_EQ_ChannelGain_dB[21]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[22]", "ParametersLong0|X_EQ_ChannelGain_dB[23]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[24]", "ParametersLong0|X_EQ_ChannelGain_dB[25]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[26]", "ParametersLong0|X_EQ_ChannelGain_dB[27]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[28]", "ParametersLong0|X_EQ_ChannelGain_dB[29]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[30]", "ParametersLong0|X_EQ_ChannelGain_dB[31]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[32]", "ParametersLong0|X_EQ_ChannelGain_dB[33]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[34]", "ParametersLong0|X_EQ_ChannelGain_dB[35]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[36]", "ParametersLong0|X_EQ_ChannelGain_dB[37]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[38]", "ParametersLong0|X_EQ_ChannelGain_dB[39]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[40]", "ParametersLong0|X_EQ_ChannelGain_dB[41]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[42]", "ParametersLong0|X_EQ_ChannelGain_dB[43]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[44]", "ParametersLong0|X_EQ_ChannelGain_dB[45]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[46]", "ParametersLong0|X_EQ_ChannelGain_dB[47]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[48]"],
            "X_FBC": ["ParametersLong0|X_FBC_ActiveSensitivity", "ParametersLong0|X_FBC_ActiveSpeed",
                      "ParametersLong0|X_FBC_ActiveTime", "ParametersLong0|X_FBC_Enable",
                      "ParametersLong0|X_FBC_GainManagementEnable", "ParametersLong0|X_FBC_GainManagementLimit",
                      "ParametersLong0|X_FBC_IdleSpeed", "ParametersLong0|X_FBC_LeakFast",
                      "ParametersLong0|X_FBC_LeakNorm", "ParametersLong0|X_FBC_NormalizationBias"],
            "X_FE": ["ParametersLong0|X_FE_AUXEQEnable", "ParametersLong0|X_FE_AUXHighBandGaindB",
                     "ParametersLong0|X_FE_AUXLowBandGaindB", "ParametersLong0|X_FE_FEMode",
                     "ParametersLong0|X_FE_NullAngle"], "X_LIM": ["ParametersLong0|X_LIM_TargetGain_dB"],
            "X_NR": ["ParametersLong0|X_NR_MaxDepth[0]", "ParametersLong0|X_NR_MaxDepth[1]",
                     "ParametersLong0|X_NR_MaxDepth[2]", "ParametersLong0|X_NR_MaxDepth[3]",
                     "ParametersLong0|X_NR_MaxDepth[4]", "ParametersLong0|X_NR_MaxDepth[5]",
                     "ParametersLong0|X_NR_MaxDepth[6]", "ParametersLong0|X_NR_MaxDepth[7]",
                     "ParametersLong0|X_NR_MaxDepth[8]", "ParametersLong0|X_NR_MaxDepth[9]",
                     "ParametersLong0|X_NR_MaxDepth[10]", "ParametersLong0|X_NR_MaxDepth[11]",
                     "ParametersLong0|X_NR_MaxDepth[12]", "ParametersLong0|X_NR_MaxDepth[13]",
                     "ParametersLong0|X_NR_MaxDepth[14]", "ParametersLong0|X_NR_MaxDepth[15]",
                     "ParametersLong0|X_NR_MaxDepth[16]", "ParametersLong0|X_NR_MaxDepth[17]",
                     "ParametersLong0|X_NR_MaxDepth[18]", "ParametersLong0|X_NR_MaxDepth[19]",
                     "ParametersLong0|X_NR_MaxDepth[20]", "ParametersLong0|X_NR_MaxDepth[21]",
                     "ParametersLong0|X_NR_MaxDepth[22]", "ParametersLong0|X_NR_MaxDepth[23]",
                     "ParametersLong0|X_NR_MaxDepth[24]", "ParametersLong0|X_NR_MaxDepth[25]",
                     "ParametersLong0|X_NR_MaxDepth[26]", "ParametersLong0|X_NR_MaxDepth[27]",
                     "ParametersLong0|X_NR_MaxDepth[28]", "ParametersLong0|X_NR_MaxDepth[29]",
                     "ParametersLong0|X_NR_MaxDepth[30]", "ParametersLong0|X_NR_MaxDepth[31]",
                     "ParametersLong0|X_NR_MaxDepth[32]", "ParametersLong0|X_NR_MaxDepth[33]",
                     "ParametersLong0|X_NR_MaxDepth[34]", "ParametersLong0|X_NR_MaxDepth[35]",
                     "ParametersLong0|X_NR_MaxDepth[36]", "ParametersLong0|X_NR_MaxDepth[37]",
                     "ParametersLong0|X_NR_MaxDepth[38]", "ParametersLong0|X_NR_MaxDepth[39]",
                     "ParametersLong0|X_NR_MaxDepth[40]", "ParametersLong0|X_NR_MaxDepth[41]",
                     "ParametersLong0|X_NR_MaxDepth[42]", "ParametersLong0|X_NR_MaxDepth[43]",
                     "ParametersLong0|X_NR_MaxDepth[44]", "ParametersLong0|X_NR_MaxDepth[45]",
                     "ParametersLong0|X_NR_MaxDepth[46]", "ParametersLong0|X_NR_MaxDepth[47]",
                     "ParametersLong0|X_NR_MaxDepth[48]"],
            "X_SG": ["ParametersLong0|X_SG_Bandwidth", "ParametersLong0|X_SG_Centerband",
                     "ParametersLong0|X_SG_EnableMode", "ParametersLong0|X_SG_Level"],
            "X_WDRC": ["ParametersLong0|X_WDRC_ChannelOutputLimit[0]", "ParametersLong0|X_WDRC_ChannelOutputLimit[1]",
                       "ParametersLong0|X_WDRC_ChannelOutputLimit[2]", "ParametersLong0|X_WDRC_ChannelOutputLimit[3]",
                       "ParametersLong0|X_WDRC_ChannelOutputLimit[4]", "ParametersLong0|X_WDRC_ChannelOutputLimit[5]",
                       "ParametersLong0|X_WDRC_ChannelOutputLimit[6]", "ParametersLong0|X_WDRC_ChannelOutputLimit[7]",
                       "ParametersLong0|X_WDRC_ChannelOutputLimit[8]", "ParametersLong0|X_WDRC_ChannelOutputLimit[9]",
                       "ParametersLong0|X_WDRC_ChannelOutputLimit[10]", "ParametersLong0|X_WDRC_ChannelOutputLimit[11]",
                       "ParametersLong0|X_WDRC_ChannelOutputLimit[12]", "ParametersLong0|X_WDRC_ChannelOutputLimit[13]",
                       "ParametersLong0|X_WDRC_ChannelOutputLimit[14]", "ParametersLong0|X_WDRC_ChannelOutputLimit[15]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[0]", "ParametersLong0|X_WDRC_ExpansionAttackTime[1]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[2]", "ParametersLong0|X_WDRC_ExpansionAttackTime[3]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[4]", "ParametersLong0|X_WDRC_ExpansionAttackTime[5]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[6]", "ParametersLong0|X_WDRC_ExpansionAttackTime[7]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[8]", "ParametersLong0|X_WDRC_ExpansionAttackTime[9]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[10]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[11]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[12]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[13]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[14]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[15]", "ParametersLong0|X_WDRC_ExpansionEnable[0]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[1]", "ParametersLong0|X_WDRC_ExpansionEnable[2]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[3]", "ParametersLong0|X_WDRC_ExpansionEnable[4]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[5]", "ParametersLong0|X_WDRC_ExpansionEnable[6]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[7]", "ParametersLong0|X_WDRC_ExpansionEnable[8]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[9]", "ParametersLong0|X_WDRC_ExpansionEnable[10]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[11]", "ParametersLong0|X_WDRC_ExpansionEnable[12]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[13]", "ParametersLong0|X_WDRC_ExpansionEnable[14]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[15]", "ParametersLong0|X_WDRC_ExpansionRatio[0]",
                       "ParametersLong0|X_WDRC_ExpansionRatio[1]", "ParametersLong0|X_WDRC_ExpansionRatio[2]",
                       "ParametersLong0|X_WDRC_ExpansionRatio[3]", "ParametersLong0|X_WDRC_ExpansionRatio[4]",
                       "ParametersLong0|X_WDRC_ExpansionRatio[5]", "ParametersLong0|X_WDRC_ExpansionRatio[6]",
                       "ParametersLong0|X_WDRC_ExpansionRatio[7]", "ParametersLong0|X_WDRC_ExpansionRatio[8]",
                       "ParametersLong0|X_WDRC_ExpansionRatio[9]", "ParametersLong0|X_WDRC_ExpansionRatio[10]",
                       "ParametersLong0|X_WDRC_ExpansionRatio[11]", "ParametersLong0|X_WDRC_ExpansionRatio[12]",
                       "ParametersLong0|X_WDRC_ExpansionRatio[13]", "ParametersLong0|X_WDRC_ExpansionRatio[14]",
                       "ParametersLong0|X_WDRC_ExpansionRatio[15]", "ParametersLong0|X_WDRC_ExpansionReleaseTime[0]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[1]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[2]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[3]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[4]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[5]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[6]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[7]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[8]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[9]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[10]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[11]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[12]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[13]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[14]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[15]",
                       "ParametersLong0|X_WDRC_HighLevelThreshold[0]", "ParametersLong0|X_WDRC_HighLevelThreshold[1]",
                       "ParametersLong0|X_WDRC_HighLevelThreshold[2]", "ParametersLong0|X_WDRC_HighLevelThreshold[3]",
                       "ParametersLong0|X_WDRC_HighLevelThreshold[4]", "ParametersLong0|X_WDRC_HighLevelThreshold[5]",
                       "ParametersLong0|X_WDRC_HighLevelThreshold[6]", "ParametersLong0|X_WDRC_HighLevelThreshold[7]",
                       "ParametersLong0|X_WDRC_HighLevelThreshold[8]", "ParametersLong0|X_WDRC_HighLevelThreshold[9]",
                       "ParametersLong0|X_WDRC_HighLevelThreshold[10]", "ParametersLong0|X_WDRC_HighLevelThreshold[11]",
                       "ParametersLong0|X_WDRC_HighLevelThreshold[12]", "ParametersLong0|X_WDRC_HighLevelThreshold[13]",
                       "ParametersLong0|X_WDRC_HighLevelThreshold[14]", "ParametersLong0|X_WDRC_HighLevelThreshold[15]",
                       "ParametersLong0|X_WDRC_LimitAttackTime[0]", "ParametersLong0|X_WDRC_LimitAttackTime[1]",
                       "ParametersLong0|X_WDRC_LimitAttackTime[2]", "ParametersLong0|X_WDRC_LimitAttackTime[3]",
                       "ParametersLong0|X_WDRC_LimitAttackTime[4]", "ParametersLong0|X_WDRC_LimitAttackTime[5]",
                       "ParametersLong0|X_WDRC_LimitAttackTime[6]", "ParametersLong0|X_WDRC_LimitAttackTime[7]",
                       "ParametersLong0|X_WDRC_LimitAttackTime[8]", "ParametersLong0|X_WDRC_LimitAttackTime[9]",
                       "ParametersLong0|X_WDRC_LimitAttackTime[10]", "ParametersLong0|X_WDRC_LimitAttackTime[11]",
                       "ParametersLong0|X_WDRC_LimitAttackTime[12]", "ParametersLong0|X_WDRC_LimitAttackTime[13]",
                       "ParametersLong0|X_WDRC_LimitAttackTime[14]", "ParametersLong0|X_WDRC_LimitAttackTime[15]",
                       "ParametersLong0|X_WDRC_LimitReleaseTime[0]", "ParametersLong0|X_WDRC_LimitReleaseTime[1]",
                       "ParametersLong0|X_WDRC_LimitReleaseTime[2]", "ParametersLong0|X_WDRC_LimitReleaseTime[3]",
                       "ParametersLong0|X_WDRC_LimitReleaseTime[4]", "ParametersLong0|X_WDRC_LimitReleaseTime[5]",
                       "ParametersLong0|X_WDRC_LimitReleaseTime[6]", "ParametersLong0|X_WDRC_LimitReleaseTime[7]",
                       "ParametersLong0|X_WDRC_LimitReleaseTime[8]", "ParametersLong0|X_WDRC_LimitReleaseTime[9]",
                       "ParametersLong0|X_WDRC_LimitReleaseTime[10]", "ParametersLong0|X_WDRC_LimitReleaseTime[11]",
                       "ParametersLong0|X_WDRC_LimitReleaseTime[12]", "ParametersLong0|X_WDRC_LimitReleaseTime[13]",
                       "ParametersLong0|X_WDRC_LimitReleaseTime[14]", "ParametersLong0|X_WDRC_LimitReleaseTime[15]",
                       "ParametersLong0|X_WDRC_LowLevelThreshold[0]", "ParametersLong0|X_WDRC_LowLevelThreshold[1]",
                       "ParametersLong0|X_WDRC_LowLevelThreshold[2]", "ParametersLong0|X_WDRC_LowLevelThreshold[3]",
                       "ParametersLong0|X_WDRC_LowLevelThreshold[4]", "ParametersLong0|X_WDRC_LowLevelThreshold[5]",
                       "ParametersLong0|X_WDRC_LowLevelThreshold[6]", "ParametersLong0|X_WDRC_LowLevelThreshold[7]",
                       "ParametersLong0|X_WDRC_LowLevelThreshold[8]", "ParametersLong0|X_WDRC_LowLevelThreshold[9]",
                       "ParametersLong0|X_WDRC_LowLevelThreshold[10]", "ParametersLong0|X_WDRC_LowLevelThreshold[11]",
                       "ParametersLong0|X_WDRC_LowLevelThreshold[12]", "ParametersLong0|X_WDRC_LowLevelThreshold[13]",
                       "ParametersLong0|X_WDRC_LowLevelThreshold[14]", "ParametersLong0|X_WDRC_LowLevelThreshold[15]",
                       "ParametersLong0|X_WDRC_PrimaryAttackTime[0]", "ParametersLong0|X_WDRC_PrimaryAttackTime[1]",
                       "ParametersLong0|X_WDRC_PrimaryAttackTime[2]", "ParametersLong0|X_WDRC_PrimaryAttackTime[3]",
                       "ParametersLong0|X_WDRC_PrimaryAttackTime[4]", "ParametersLong0|X_WDRC_PrimaryAttackTime[5]",
                       "ParametersLong0|X_WDRC_PrimaryAttackTime[6]", "ParametersLong0|X_WDRC_PrimaryAttackTime[7]",
                       "ParametersLong0|X_WDRC_PrimaryAttackTime[8]", "ParametersLong0|X_WDRC_PrimaryAttackTime[9]",
                       "ParametersLong0|X_WDRC_PrimaryAttackTime[10]", "ParametersLong0|X_WDRC_PrimaryAttackTime[11]",
                       "ParametersLong0|X_WDRC_PrimaryAttackTime[12]", "ParametersLong0|X_WDRC_PrimaryAttackTime[13]",
                       "ParametersLong0|X_WDRC_PrimaryAttackTime[14]", "ParametersLong0|X_WDRC_PrimaryAttackTime[15]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[0]", "ParametersLong0|X_WDRC_PrimaryReleaseTime[1]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[2]", "ParametersLong0|X_WDRC_PrimaryReleaseTime[3]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[4]", "ParametersLong0|X_WDRC_PrimaryReleaseTime[5]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[6]", "ParametersLong0|X_WDRC_PrimaryReleaseTime[7]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[8]", "ParametersLong0|X_WDRC_PrimaryReleaseTime[9]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[10]", "ParametersLong0|X_WDRC_PrimaryReleaseTime[11]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[12]", "ParametersLong0|X_WDRC_PrimaryReleaseTime[13]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[14]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[15]"],
            "WDRC_LV": ["ParametersLong0|X_WDRC_HighLevelGain[0]", "ParametersLong0|X_WDRC_HighLevelGain[1]",
                        "ParametersLong0|X_WDRC_HighLevelGain[2]", "ParametersLong0|X_WDRC_HighLevelGain[3]",
                        "ParametersLong0|X_WDRC_HighLevelGain[4]", "ParametersLong0|X_WDRC_HighLevelGain[5]",
                        "ParametersLong0|X_WDRC_HighLevelGain[6]", "ParametersLong0|X_WDRC_HighLevelGain[7]",
                        "ParametersLong0|X_WDRC_HighLevelGain[8]", "ParametersLong0|X_WDRC_HighLevelGain[9]",
                        "ParametersLong0|X_WDRC_HighLevelGain[10]", "ParametersLong0|X_WDRC_HighLevelGain[11]",
                        "ParametersLong0|X_WDRC_HighLevelGain[12]", "ParametersLong0|X_WDRC_HighLevelGain[13]",
                        "ParametersLong0|X_WDRC_HighLevelGain[14]", "ParametersLong0|X_WDRC_HighLevelGain[15]",
                        "ParametersLong0|X_WDRC_LowLevelGain[0]", "ParametersLong0|X_WDRC_LowLevelGain[1]",
                        "ParametersLong0|X_WDRC_LowLevelGain[2]", "ParametersLong0|X_WDRC_LowLevelGain[3]",
                        "ParametersLong0|X_WDRC_LowLevelGain[4]", "ParametersLong0|X_WDRC_LowLevelGain[5]",
                        "ParametersLong0|X_WDRC_LowLevelGain[6]", "ParametersLong0|X_WDRC_LowLevelGain[7]",
                        "ParametersLong0|X_WDRC_LowLevelGain[8]", "ParametersLong0|X_WDRC_LowLevelGain[9]",
                        "ParametersLong0|X_WDRC_LowLevelGain[10]", "ParametersLong0|X_WDRC_LowLevelGain[11]",
                        "ParametersLong0|X_WDRC_LowLevelGain[12]", "ParametersLong0|X_WDRC_LowLevelGain[13]",
                        "ParametersLong0|X_WDRC_LowLevelGain[14]", "ParametersLong0|X_WDRC_LowLevelGain[15]"]}

e7111_all_keys = {"OTHERS": ["ParametersDouble0|X_AuxiliaryAttenuation", "ParametersDouble0|X_MicrophoneAttenuation",
                       "ParametersLong0|X_AuxiliaryInput", "ParametersLong0|X_LIM_TargetGain_dB"],
            "X_AuxiliaryAttenuation": ["ParametersDouble0|X_AuxiliaryAttenuation"],
            "X_HC": ["ParametersDouble0|X_HC_PostBiquad0Coeffa1", "ParametersDouble0|X_HC_PostBiquad0Coeffa2",
                     "ParametersDouble0|X_HC_PostBiquad0Coeffb0", "ParametersDouble0|X_HC_PostBiquad0Coeffb1",
                     "ParametersDouble0|X_HC_PostBiquad0Coeffb2", "ParametersDouble0|X_HC_PostBiquad1Coeffa1",
                     "ParametersDouble0|X_HC_PostBiquad1Coeffa2", "ParametersDouble0|X_HC_PostBiquad1Coeffb0",
                     "ParametersDouble0|X_HC_PostBiquad1Coeffb1", "ParametersDouble0|X_HC_PostBiquad1Coeffb2",
                     "ParametersDouble0|X_HC_PostBiquad2Coeffa1", "ParametersDouble0|X_HC_PostBiquad2Coeffa2",
                     "ParametersDouble0|X_HC_PostBiquad2Coeffb0", "ParametersDouble0|X_HC_PostBiquad2Coeffb1",
                     "ParametersDouble0|X_HC_PostBiquad2Coeffb2", "ParametersDouble0|X_HC_PostBiquad3Coeffa1",
                     "ParametersDouble0|X_HC_PostBiquad3Coeffa2", "ParametersDouble0|X_HC_PostBiquad3Coeffb0",
                     "ParametersDouble0|X_HC_PostBiquad3Coeffb1", "ParametersDouble0|X_HC_PostBiquad3Coeffb2",
                     "ParametersDouble0|X_HC_PreBiquad0Coeffa1", "ParametersDouble0|X_HC_PreBiquad0Coeffa2",
                     "ParametersDouble0|X_HC_PreBiquad0Coeffb0", "ParametersDouble0|X_HC_PreBiquad0Coeffb1",
                     "ParametersDouble0|X_HC_PreBiquad0Coeffb2", "ParametersDouble0|X_HC_PreBiquad1Coeffa1",
                     "ParametersDouble0|X_HC_PreBiquad1Coeffa2", "ParametersDouble0|X_HC_PreBiquad1Coeffb0",
                     "ParametersDouble0|X_HC_PreBiquad1Coeffb1", "ParametersDouble0|X_HC_PreBiquad1Coeffb2",
                     "ParametersDouble0|X_HC_PreBiquad2Coeffa1", "ParametersDouble0|X_HC_PreBiquad2Coeffa2",
                     "ParametersDouble0|X_HC_PreBiquad2Coeffb0", "ParametersDouble0|X_HC_PreBiquad2Coeffb1",
                     "ParametersDouble0|X_HC_PreBiquad2Coeffb2", "ParametersDouble0|X_HC_PreBiquad3Coeffa1",
                     "ParametersDouble0|X_HC_PreBiquad3Coeffa2", "ParametersDouble0|X_HC_PreBiquad3Coeffb0",
                     "ParametersDouble0|X_HC_PreBiquad3Coeffb1", "ParametersDouble0|X_HC_PreBiquad3Coeffb2"],
            "X_MicrophoneAttenuation": ["ParametersDouble0|X_MicrophoneAttenuation"],
            "X_AuxiliaryInput": ["ParametersLong0|X_AuxiliaryInput"],
            "X_EQ": ["ParametersLong0|X_EQ_ChannelGain_dB[0]", "ParametersLong0|X_EQ_ChannelGain_dB[1]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[2]", "ParametersLong0|X_EQ_ChannelGain_dB[3]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[4]", "ParametersLong0|X_EQ_ChannelGain_dB[5]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[6]", "ParametersLong0|X_EQ_ChannelGain_dB[7]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[8]", "ParametersLong0|X_EQ_ChannelGain_dB[9]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[10]", "ParametersLong0|X_EQ_ChannelGain_dB[11]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[12]", "ParametersLong0|X_EQ_ChannelGain_dB[13]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[14]", "ParametersLong0|X_EQ_ChannelGain_dB[15]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[16]", "ParametersLong0|X_EQ_ChannelGain_dB[17]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[18]", "ParametersLong0|X_EQ_ChannelGain_dB[19]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[20]", "ParametersLong0|X_EQ_ChannelGain_dB[21]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[22]", "ParametersLong0|X_EQ_ChannelGain_dB[23]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[24]", "ParametersLong0|X_EQ_ChannelGain_dB[25]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[26]", "ParametersLong0|X_EQ_ChannelGain_dB[27]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[28]", "ParametersLong0|X_EQ_ChannelGain_dB[29]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[30]", "ParametersLong0|X_EQ_ChannelGain_dB[31]",
                     "ParametersLong0|X_EQ_ChannelGain_dB[32]"],
            "X_FBC": ["ParametersLong0|X_FBC_ActiveSensitivity", "ParametersLong0|X_FBC_ActiveSpeed",
                      "ParametersLong0|X_FBC_ActiveTime", "ParametersLong0|X_FBC_Enable",
                      "ParametersLong0|X_FBC_GainManagementEnable", "ParametersLong0|X_FBC_GainManagementLimit",
                      "ParametersLong0|X_FBC_IdleSpeed", "ParametersLong0|X_FBC_LeakFast",
                      "ParametersLong0|X_FBC_LeakNorm", "ParametersLong0|X_FBC_NormalizationBias"],
            "X_FE": ["ParametersLong0|X_FE_FEMode","ParametersLong0|X_FE_NullAngle"], "X_LIM": ["ParametersLong0|X_LIM_TargetGain_dB"],
            "X_NR": ["ParametersLong0|X_NR_MaxDepth[0]", "ParametersLong0|X_NR_MaxDepth[1]",
                     "ParametersLong0|X_NR_MaxDepth[2]", "ParametersLong0|X_NR_MaxDepth[3]",
                     "ParametersLong0|X_NR_MaxDepth[4]", "ParametersLong0|X_NR_MaxDepth[5]",
                     "ParametersLong0|X_NR_MaxDepth[6]", "ParametersLong0|X_NR_MaxDepth[7]",
                     "ParametersLong0|X_NR_MaxDepth[8]", "ParametersLong0|X_NR_MaxDepth[9]",
                     "ParametersLong0|X_NR_MaxDepth[10]", "ParametersLong0|X_NR_MaxDepth[11]",
                     "ParametersLong0|X_NR_MaxDepth[12]", "ParametersLong0|X_NR_MaxDepth[13]",
                     "ParametersLong0|X_NR_MaxDepth[14]", "ParametersLong0|X_NR_MaxDepth[15]",
                     "ParametersLong0|X_NR_MaxDepth[16]", "ParametersLong0|X_NR_MaxDepth[17]",
                     "ParametersLong0|X_NR_MaxDepth[18]", "ParametersLong0|X_NR_MaxDepth[19]",
                     "ParametersLong0|X_NR_MaxDepth[20]", "ParametersLong0|X_NR_MaxDepth[21]",
                     "ParametersLong0|X_NR_MaxDepth[22]", "ParametersLong0|X_NR_MaxDepth[23]",
                     "ParametersLong0|X_NR_MaxDepth[24]", "ParametersLong0|X_NR_MaxDepth[25]",
                     "ParametersLong0|X_NR_MaxDepth[26]", "ParametersLong0|X_NR_MaxDepth[27]",
                     "ParametersLong0|X_NR_MaxDepth[28]", "ParametersLong0|X_NR_MaxDepth[29]",
                     "ParametersLong0|X_NR_MaxDepth[30]", "ParametersLong0|X_NR_MaxDepth[31]",
                     "ParametersLong0|X_NR_MaxDepth[32]"],
            "X_WDRC": ["ParametersLong0|X_WDRC_ChannelOutputLimit[0]", "ParametersLong0|X_WDRC_ChannelOutputLimit[1]",
                       "ParametersLong0|X_WDRC_ChannelOutputLimit[2]", "ParametersLong0|X_WDRC_ChannelOutputLimit[3]",
                       "ParametersLong0|X_WDRC_ChannelOutputLimit[4]", "ParametersLong0|X_WDRC_ChannelOutputLimit[5]",
                       "ParametersLong0|X_WDRC_ChannelOutputLimit[6]", "ParametersLong0|X_WDRC_ChannelOutputLimit[7]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[0]", "ParametersLong0|X_WDRC_ExpansionAttackTime[1]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[2]", "ParametersLong0|X_WDRC_ExpansionAttackTime[3]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[4]", "ParametersLong0|X_WDRC_ExpansionAttackTime[5]",
                       "ParametersLong0|X_WDRC_ExpansionAttackTime[6]", "ParametersLong0|X_WDRC_ExpansionAttackTime[7]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[0]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[1]", "ParametersLong0|X_WDRC_ExpansionEnable[2]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[3]", "ParametersLong0|X_WDRC_ExpansionEnable[4]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[5]", "ParametersLong0|X_WDRC_ExpansionEnable[6]",
                       "ParametersLong0|X_WDRC_ExpansionEnable[7]", "ParametersLong0|X_WDRC_ExpansionRatio[0]",
                       "ParametersLong0|X_WDRC_ExpansionRatio[1]", "ParametersLong0|X_WDRC_ExpansionRatio[2]",
                       "ParametersLong0|X_WDRC_ExpansionRatio[3]", "ParametersLong0|X_WDRC_ExpansionRatio[4]",
                       "ParametersLong0|X_WDRC_ExpansionRatio[5]", "ParametersLong0|X_WDRC_ExpansionRatio[6]",
                       "ParametersLong0|X_WDRC_ExpansionRatio[7]", "ParametersLong0|X_WDRC_ExpansionReleaseTime[0]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[1]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[2]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[3]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[4]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[5]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[6]",
                       "ParametersLong0|X_WDRC_ExpansionReleaseTime[7]",
                       "ParametersLong0|X_WDRC_HighLevelThreshold[0]", "ParametersLong0|X_WDRC_HighLevelThreshold[1]",
                       "ParametersLong0|X_WDRC_HighLevelThreshold[2]", "ParametersLong0|X_WDRC_HighLevelThreshold[3]",
                       "ParametersLong0|X_WDRC_HighLevelThreshold[4]", "ParametersLong0|X_WDRC_HighLevelThreshold[5]",
                       "ParametersLong0|X_WDRC_HighLevelThreshold[6]", "ParametersLong0|X_WDRC_HighLevelThreshold[7]",
                       "ParametersLong0|X_WDRC_LimitAttackTime[0]", "ParametersLong0|X_WDRC_LimitAttackTime[1]",
                       "ParametersLong0|X_WDRC_LimitAttackTime[2]", "ParametersLong0|X_WDRC_LimitAttackTime[3]",
                       "ParametersLong0|X_WDRC_LimitAttackTime[4]", "ParametersLong0|X_WDRC_LimitAttackTime[5]",
                       "ParametersLong0|X_WDRC_LimitAttackTime[6]", "ParametersLong0|X_WDRC_LimitAttackTime[7]",
                       "ParametersLong0|X_WDRC_LimitReleaseTime[0]", "ParametersLong0|X_WDRC_LimitReleaseTime[1]",
                       "ParametersLong0|X_WDRC_LimitReleaseTime[2]", "ParametersLong0|X_WDRC_LimitReleaseTime[3]",
                       "ParametersLong0|X_WDRC_LimitReleaseTime[4]", "ParametersLong0|X_WDRC_LimitReleaseTime[5]",
                       "ParametersLong0|X_WDRC_LimitReleaseTime[6]", "ParametersLong0|X_WDRC_LimitReleaseTime[7]",
                       "ParametersLong0|X_WDRC_LowLevelThreshold[0]", "ParametersLong0|X_WDRC_LowLevelThreshold[1]",
                       "ParametersLong0|X_WDRC_LowLevelThreshold[2]", "ParametersLong0|X_WDRC_LowLevelThreshold[3]",
                       "ParametersLong0|X_WDRC_LowLevelThreshold[4]", "ParametersLong0|X_WDRC_LowLevelThreshold[5]",
                       "ParametersLong0|X_WDRC_LowLevelThreshold[6]", "ParametersLong0|X_WDRC_LowLevelThreshold[7]",
                       "ParametersLong0|X_WDRC_PrimaryAttackTime[0]", "ParametersLong0|X_WDRC_PrimaryAttackTime[1]",
                       "ParametersLong0|X_WDRC_PrimaryAttackTime[2]", "ParametersLong0|X_WDRC_PrimaryAttackTime[3]",
                       "ParametersLong0|X_WDRC_PrimaryAttackTime[4]", "ParametersLong0|X_WDRC_PrimaryAttackTime[5]",
                       "ParametersLong0|X_WDRC_PrimaryAttackTime[6]", "ParametersLong0|X_WDRC_PrimaryAttackTime[7]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[0]", "ParametersLong0|X_WDRC_PrimaryReleaseTime[1]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[2]", "ParametersLong0|X_WDRC_PrimaryReleaseTime[3]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[4]", "ParametersLong0|X_WDRC_PrimaryReleaseTime[5]",
                       "ParametersLong0|X_WDRC_PrimaryReleaseTime[6]", "ParametersLong0|X_WDRC_PrimaryReleaseTime[7]"],
            "WDRC_LV": ["ParametersLong0|X_WDRC_HighLevelGain[0]", "ParametersLong0|X_WDRC_HighLevelGain[1]",
                        "ParametersLong0|X_WDRC_HighLevelGain[2]", "ParametersLong0|X_WDRC_HighLevelGain[3]",
                        "ParametersLong0|X_WDRC_HighLevelGain[4]", "ParametersLong0|X_WDRC_HighLevelGain[5]",
                        "ParametersLong0|X_WDRC_HighLevelGain[6]", "ParametersLong0|X_WDRC_HighLevelGain[7]",
                        "ParametersLong0|X_WDRC_LowLevelGain[0]", "ParametersLong0|X_WDRC_LowLevelGain[1]",
                        "ParametersLong0|X_WDRC_LowLevelGain[2]", "ParametersLong0|X_WDRC_LowLevelGain[3]",
                        "ParametersLong0|X_WDRC_LowLevelGain[4]", "ParametersLong0|X_WDRC_LowLevelGain[5]",
                        "ParametersLong0|X_WDRC_LowLevelGain[6]", "ParametersLong0|X_WDRC_LowLevelGain[7]"]}
# with open("./fitting_v1_e7111v2_keymap.json", "r") as f:
#     key_map = json.load(f)
key_map = {"ParametersDouble0|X_AuxiliaryAttenuation": [0, "ParametersDouble0|X_AuxiliaryAttenuation", -88, 12, 6],
           "ParametersDouble0|X_HC_PostBiquad0Coeffa1": [1, "ParametersDouble0|X_HC_PostBiquad0Coeffa1", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad0Coeffa2": [2, "ParametersDouble0|X_HC_PostBiquad0Coeffa2", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad0Coeffb0": [3, "ParametersDouble0|X_HC_PostBiquad0Coeffb0", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad0Coeffb1": [4, "ParametersDouble0|X_HC_PostBiquad0Coeffb1", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad0Coeffb2": [5, "ParametersDouble0|X_HC_PostBiquad0Coeffb2", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad1Coeffa1": [6, "ParametersDouble0|X_HC_PostBiquad1Coeffa1", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad1Coeffa2": [7, "ParametersDouble0|X_HC_PostBiquad1Coeffa2", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad1Coeffb0": [8, "ParametersDouble0|X_HC_PostBiquad1Coeffb0", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad1Coeffb1": [9, "ParametersDouble0|X_HC_PostBiquad1Coeffb1", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad1Coeffb2": [10, "ParametersDouble0|X_HC_PostBiquad1Coeffb2", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad2Coeffa1": [11, "ParametersDouble0|X_HC_PostBiquad2Coeffa1", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad2Coeffa2": [12, "ParametersDouble0|X_HC_PostBiquad2Coeffa2", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad2Coeffb0": [13, "ParametersDouble0|X_HC_PostBiquad2Coeffb0", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad2Coeffb1": [14, "ParametersDouble0|X_HC_PostBiquad2Coeffb1", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad2Coeffb2": [15, "ParametersDouble0|X_HC_PostBiquad2Coeffb2", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad3Coeffa1": [16, "ParametersDouble0|X_HC_PostBiquad3Coeffa1", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad3Coeffa2": [17, "ParametersDouble0|X_HC_PostBiquad3Coeffa2", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad3Coeffb0": [18, "ParametersDouble0|X_HC_PostBiquad3Coeffb0", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad3Coeffb1": [19, "ParametersDouble0|X_HC_PostBiquad3Coeffb1", -2, 2, 1],
           "ParametersDouble0|X_HC_PostBiquad3Coeffb2": [20, "ParametersDouble0|X_HC_PostBiquad3Coeffb2", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad0Coeffa1": [21, "ParametersDouble0|X_HC_PreBiquad0Coeffa1", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad0Coeffa2": [22, "ParametersDouble0|X_HC_PreBiquad0Coeffa2", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad0Coeffb0": [23, "ParametersDouble0|X_HC_PreBiquad0Coeffb0", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad0Coeffb1": [24, "ParametersDouble0|X_HC_PreBiquad0Coeffb1", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad0Coeffb2": [25, "ParametersDouble0|X_HC_PreBiquad0Coeffb2", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad1Coeffa1": [26, "ParametersDouble0|X_HC_PreBiquad1Coeffa1", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad1Coeffa2": [27, "ParametersDouble0|X_HC_PreBiquad1Coeffa2", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad1Coeffb0": [28, "ParametersDouble0|X_HC_PreBiquad1Coeffb0", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad1Coeffb1": [29, "ParametersDouble0|X_HC_PreBiquad1Coeffb1", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad1Coeffb2": [30, "ParametersDouble0|X_HC_PreBiquad1Coeffb2", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad2Coeffa1": [31, "ParametersDouble0|X_HC_PreBiquad2Coeffa1", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad2Coeffa2": [32, "ParametersDouble0|X_HC_PreBiquad2Coeffa2", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad2Coeffb0": [33, "ParametersDouble0|X_HC_PreBiquad2Coeffb0", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad2Coeffb1": [34, "ParametersDouble0|X_HC_PreBiquad2Coeffb1", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad2Coeffb2": [35, "ParametersDouble0|X_HC_PreBiquad2Coeffb2", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad3Coeffa1": [36, "ParametersDouble0|X_HC_PreBiquad3Coeffa1", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad3Coeffa2": [37, "ParametersDouble0|X_HC_PreBiquad3Coeffa2", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad3Coeffb0": [38, "ParametersDouble0|X_HC_PreBiquad3Coeffb0", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad3Coeffb1": [39, "ParametersDouble0|X_HC_PreBiquad3Coeffb1", -2, 2, 1],
           "ParametersDouble0|X_HC_PreBiquad3Coeffb2": [40, "ParametersDouble0|X_HC_PreBiquad3Coeffb2", -2, 2, 1],
           "ParametersDouble0|X_MicrophoneAttenuation": [41, "ParametersDouble0|X_MicrophoneAttenuation", -88, 12, 6],
           "ParametersLong0|X_AuxiliaryInput": [43, "ParametersLong0|X_AuxiliaryInput", 0, 1, 1],
           "ParametersLong0|X_EQ_ChannelGain_dB[0]": [44, "ParametersLong0|X_EQ_ChannelGain_dB[0]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[1]": [45, "ParametersLong0|X_EQ_ChannelGain_dB[1]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[2]": [46, "ParametersLong0|X_EQ_ChannelGain_dB[2]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[3]": [47, "ParametersLong0|X_EQ_ChannelGain_dB[3]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[4]": [48, "ParametersLong0|X_EQ_ChannelGain_dB[4]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[5]": [49, "ParametersLong0|X_EQ_ChannelGain_dB[5]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[6]": [50, "ParametersLong0|X_EQ_ChannelGain_dB[6]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[7]": [51, "ParametersLong0|X_EQ_ChannelGain_dB[7]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[8]": [52, "ParametersLong0|X_EQ_ChannelGain_dB[8]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[9]": [53, "ParametersLong0|X_EQ_ChannelGain_dB[9]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[10]": [54, "ParametersLong0|X_EQ_ChannelGain_dB[10]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[11]": [55, "ParametersLong0|X_EQ_ChannelGain_dB[11]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[12]": [56, "ParametersLong0|X_EQ_ChannelGain_dB[12]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[13]": [57, "ParametersLong0|X_EQ_ChannelGain_dB[13]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[14]": [58, "ParametersLong0|X_EQ_ChannelGain_dB[14]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[15]": [59, "ParametersLong0|X_EQ_ChannelGain_dB[15]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[16]": [60, "ParametersLong0|X_EQ_ChannelGain_dB[16]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[17]": [61, "ParametersLong0|X_EQ_ChannelGain_dB[17]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[18]": [62, "ParametersLong0|X_EQ_ChannelGain_dB[18]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[19]": [63, "ParametersLong0|X_EQ_ChannelGain_dB[19]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[20]": [64, "ParametersLong0|X_EQ_ChannelGain_dB[20]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[21]": [65, "ParametersLong0|X_EQ_ChannelGain_dB[21]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[22]": [66, "ParametersLong0|X_EQ_ChannelGain_dB[22]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[23]": [67, "ParametersLong0|X_EQ_ChannelGain_dB[23]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[24]": [68, "ParametersLong0|X_EQ_ChannelGain_dB[24]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[25]": [69, "ParametersLong0|X_EQ_ChannelGain_dB[25]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[26]": [70, "ParametersLong0|X_EQ_ChannelGain_dB[26]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[27]": [71, "ParametersLong0|X_EQ_ChannelGain_dB[27]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[28]": [72, "ParametersLong0|X_EQ_ChannelGain_dB[28]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[29]": [73, "ParametersLong0|X_EQ_ChannelGain_dB[29]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[30]": [74, "ParametersLong0|X_EQ_ChannelGain_dB[30]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[31]": [75, "ParametersLong0|X_EQ_ChannelGain_dB[31]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[32]": [76, "ParametersLong0|X_EQ_ChannelGain_dB[32]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[33]": [77, "ParametersLong0|X_EQ_ChannelGain_dB[33]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[34]": [78, "ParametersLong0|X_EQ_ChannelGain_dB[34]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[35]": [79, "ParametersLong0|X_EQ_ChannelGain_dB[35]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[36]": [80, "ParametersLong0|X_EQ_ChannelGain_dB[36]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[37]": [81, "ParametersLong0|X_EQ_ChannelGain_dB[37]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[38]": [82, "ParametersLong0|X_EQ_ChannelGain_dB[38]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[39]": [83, "ParametersLong0|X_EQ_ChannelGain_dB[39]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[40]": [84, "ParametersLong0|X_EQ_ChannelGain_dB[40]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[41]": [85, "ParametersLong0|X_EQ_ChannelGain_dB[41]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[42]": [86, "ParametersLong0|X_EQ_ChannelGain_dB[42]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[43]": [87, "ParametersLong0|X_EQ_ChannelGain_dB[43]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[44]": [88, "ParametersLong0|X_EQ_ChannelGain_dB[44]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[45]": [89, "ParametersLong0|X_EQ_ChannelGain_dB[45]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[46]": [90, "ParametersLong0|X_EQ_ChannelGain_dB[46]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[47]": [91, "ParametersLong0|X_EQ_ChannelGain_dB[47]", -18, 18, 2],
           "ParametersLong0|X_EQ_ChannelGain_dB[48]": [92, "ParametersLong0|X_EQ_ChannelGain_dB[48]", -18, 18, 2],
           "ParametersLong0|X_FBC_ActiveSensitivity": [143, "ParametersLong0|X_FBC_ActiveSensitivity", 1, 80, 4],
           "ParametersLong0|X_FBC_ActiveSpeed": [144, "ParametersLong0|X_FBC_ActiveSpeed", 1, 13, 1],
           "ParametersLong0|X_FBC_ActiveTime": [145, "ParametersLong0|X_FBC_ActiveTime", 1, 100, 5],
           "ParametersLong0|X_FBC_Enable": [146, "ParametersLong0|X_FBC_Enable", 0, 1, 1],
           "ParametersLong0|X_FBC_GainManagementEnable": [147, "ParametersLong0|X_FBC_GainManagementEnable", 0, 1, 1],
           "ParametersLong0|X_FBC_GainManagementLimit": [148, "ParametersLong0|X_FBC_GainManagementLimit", -16, 16, 2],
           "ParametersLong0|X_FBC_IdleSpeed": [197, "ParametersLong0|X_FBC_IdleSpeed", 1, 13, 1],
           "ParametersLong0|X_FBC_LeakFast": [198, "ParametersLong0|X_FBC_LeakFast", 0, 24, 2],
           "ParametersLong0|X_FBC_LeakNorm": [199, "ParametersLong0|X_FBC_LeakNorm", 0, 24, 2],
           "ParametersLong0|X_FBC_NormalizationBias": [200, "ParametersLong0|X_FBC_NormalizationBias", 0, 7, 1],
           "ParametersLong0|X_FE_AUXEQEnable": [203, "ParametersLong0|X_FE_AUXEQEnable", 0, 1, 1],
           "ParametersLong0|X_FE_AUXHighBandGaindB": [204, "ParametersLong0|X_FE_AUXHighBandGaindB", -18, 18, 2],
           "ParametersLong0|X_FE_AUXLowBandGaindB": [205, "ParametersLong0|X_FE_AUXLowBandGaindB", -18, 18, 2],
           "ParametersLong0|X_FE_FEMode": [206, "ParametersLong0|X_FE_FEMode", 0, 5, 1],
           "ParametersLong0|X_FE_NullAngle": [207, "ParametersLong0|X_FE_NullAngle", 90, 180, 5],
           "ParametersLong0|X_LIM_TargetGain_dB": [208, "ParametersLong0|X_LIM_TargetGain_dB", 0, 42, 3],
           "ParametersLong0|X_NR_MaxDepth[0]": [211, "ParametersLong0|X_NR_MaxDepth[0]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[1]": [212, "ParametersLong0|X_NR_MaxDepth[1]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[2]": [213, "ParametersLong0|X_NR_MaxDepth[2]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[3]": [214, "ParametersLong0|X_NR_MaxDepth[3]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[4]": [215, "ParametersLong0|X_NR_MaxDepth[4]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[5]": [216, "ParametersLong0|X_NR_MaxDepth[5]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[6]": [217, "ParametersLong0|X_NR_MaxDepth[6]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[7]": [218, "ParametersLong0|X_NR_MaxDepth[7]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[8]": [219, "ParametersLong0|X_NR_MaxDepth[8]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[9]": [220, "ParametersLong0|X_NR_MaxDepth[9]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[10]": [221, "ParametersLong0|X_NR_MaxDepth[10]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[11]": [222, "ParametersLong0|X_NR_MaxDepth[11]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[12]": [223, "ParametersLong0|X_NR_MaxDepth[12]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[13]": [224, "ParametersLong0|X_NR_MaxDepth[13]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[14]": [225, "ParametersLong0|X_NR_MaxDepth[14]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[15]": [226, "ParametersLong0|X_NR_MaxDepth[15]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[16]": [227, "ParametersLong0|X_NR_MaxDepth[16]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[17]": [228, "ParametersLong0|X_NR_MaxDepth[17]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[18]": [229, "ParametersLong0|X_NR_MaxDepth[18]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[19]": [230, "ParametersLong0|X_NR_MaxDepth[19]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[20]": [231, "ParametersLong0|X_NR_MaxDepth[20]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[21]": [232, "ParametersLong0|X_NR_MaxDepth[21]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[22]": [233, "ParametersLong0|X_NR_MaxDepth[22]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[23]": [234, "ParametersLong0|X_NR_MaxDepth[23]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[24]": [235, "ParametersLong0|X_NR_MaxDepth[24]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[25]": [236, "ParametersLong0|X_NR_MaxDepth[25]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[26]": [237, "ParametersLong0|X_NR_MaxDepth[26]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[27]": [238, "ParametersLong0|X_NR_MaxDepth[27]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[28]": [239, "ParametersLong0|X_NR_MaxDepth[28]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[29]": [240, "ParametersLong0|X_NR_MaxDepth[29]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[30]": [241, "ParametersLong0|X_NR_MaxDepth[30]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[31]": [242, "ParametersLong0|X_NR_MaxDepth[31]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[32]": [243, "ParametersLong0|X_NR_MaxDepth[32]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[33]": [244, "ParametersLong0|X_NR_MaxDepth[33]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[34]": [245, "ParametersLong0|X_NR_MaxDepth[34]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[35]": [246, "ParametersLong0|X_NR_MaxDepth[35]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[36]": [247, "ParametersLong0|X_NR_MaxDepth[36]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[37]": [248, "ParametersLong0|X_NR_MaxDepth[37]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[38]": [249, "ParametersLong0|X_NR_MaxDepth[38]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[39]": [250, "ParametersLong0|X_NR_MaxDepth[39]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[40]": [251, "ParametersLong0|X_NR_MaxDepth[40]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[41]": [252, "ParametersLong0|X_NR_MaxDepth[41]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[42]": [253, "ParametersLong0|X_NR_MaxDepth[42]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[43]": [254, "ParametersLong0|X_NR_MaxDepth[43]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[44]": [255, "ParametersLong0|X_NR_MaxDepth[44]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[45]": [256, "ParametersLong0|X_NR_MaxDepth[45]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[46]": [257, "ParametersLong0|X_NR_MaxDepth[46]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[47]": [258, "ParametersLong0|X_NR_MaxDepth[47]", 0, 15, 1],
           "ParametersLong0|X_NR_MaxDepth[48]": [259, "ParametersLong0|X_NR_MaxDepth[48]", 0, 15, 1],
           "ParametersLong0|X_SG_Bandwidth": [260, "ParametersLong0|X_SG_Bandwidth", 1, 95, 5],
           "ParametersLong0|X_SG_Centerband": [261, "ParametersLong0|X_SG_Centerband", 1, 47, 3],
           "ParametersLong0|X_SG_EnableMode": [271, "ParametersLong0|X_SG_EnableMode", 0, 1, 1],
           "ParametersLong0|X_SG_Level": [272, "ParametersLong0|X_SG_Level", -128, 0, 7],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[0]": [274, "ParametersLong0|X_WDRC_ChannelOutputLimit[0]", -60, 0,
                                                            4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[1]": [275, "ParametersLong0|X_WDRC_ChannelOutputLimit[1]", -60, 0,
                                                            4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[2]": [276, "ParametersLong0|X_WDRC_ChannelOutputLimit[2]", -60, 0,
                                                            4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[3]": [277, "ParametersLong0|X_WDRC_ChannelOutputLimit[3]", -60, 0,
                                                            4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[4]": [278, "ParametersLong0|X_WDRC_ChannelOutputLimit[4]", -60, 0,
                                                            4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[5]": [279, "ParametersLong0|X_WDRC_ChannelOutputLimit[5]", -60, 0,
                                                            4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[6]": [280, "ParametersLong0|X_WDRC_ChannelOutputLimit[6]", -60, 0,
                                                            4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[7]": [281, "ParametersLong0|X_WDRC_ChannelOutputLimit[7]", -60, 0,
                                                            4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[8]": [282, "ParametersLong0|X_WDRC_ChannelOutputLimit[8]", -60, 0,
                                                            4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[9]": [283, "ParametersLong0|X_WDRC_ChannelOutputLimit[9]", -60, 0,
                                                            4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[10]": [284, "ParametersLong0|X_WDRC_ChannelOutputLimit[10]", -60,
                                                             0, 4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[11]": [285, "ParametersLong0|X_WDRC_ChannelOutputLimit[11]", -60,
                                                             0, 4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[12]": [286, "ParametersLong0|X_WDRC_ChannelOutputLimit[12]", -60,
                                                             0, 4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[13]": [287, "ParametersLong0|X_WDRC_ChannelOutputLimit[13]", -60,
                                                             0, 4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[14]": [288, "ParametersLong0|X_WDRC_ChannelOutputLimit[14]", -60,
                                                             0, 4],
           "ParametersLong0|X_WDRC_ChannelOutputLimit[15]": [289, "ParametersLong0|X_WDRC_ChannelOutputLimit[15]", -60,
                                                             0, 4],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[0]": [306, "ParametersLong0|X_WDRC_ExpansionAttackTime[0]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[1]": [307, "ParametersLong0|X_WDRC_ExpansionAttackTime[1]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[2]": [308, "ParametersLong0|X_WDRC_ExpansionAttackTime[2]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[3]": [309, "ParametersLong0|X_WDRC_ExpansionAttackTime[3]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[4]": [310, "ParametersLong0|X_WDRC_ExpansionAttackTime[4]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[5]": [311, "ParametersLong0|X_WDRC_ExpansionAttackTime[5]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[6]": [312, "ParametersLong0|X_WDRC_ExpansionAttackTime[6]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[7]": [313, "ParametersLong0|X_WDRC_ExpansionAttackTime[7]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[8]": [314, "ParametersLong0|X_WDRC_ExpansionAttackTime[8]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[9]": [315, "ParametersLong0|X_WDRC_ExpansionAttackTime[9]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[10]": [316, "ParametersLong0|X_WDRC_ExpansionAttackTime[10]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[11]": [317, "ParametersLong0|X_WDRC_ExpansionAttackTime[11]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[12]": [318, "ParametersLong0|X_WDRC_ExpansionAttackTime[12]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[13]": [319, "ParametersLong0|X_WDRC_ExpansionAttackTime[13]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[14]": [320, "ParametersLong0|X_WDRC_ExpansionAttackTime[14]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionAttackTime[15]": [321, "ParametersLong0|X_WDRC_ExpansionAttackTime[15]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[0]": [322, "ParametersLong0|X_WDRC_ExpansionEnable[0]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[1]": [323, "ParametersLong0|X_WDRC_ExpansionEnable[1]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[2]": [324, "ParametersLong0|X_WDRC_ExpansionEnable[2]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[3]": [325, "ParametersLong0|X_WDRC_ExpansionEnable[3]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[4]": [326, "ParametersLong0|X_WDRC_ExpansionEnable[4]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[5]": [327, "ParametersLong0|X_WDRC_ExpansionEnable[5]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[6]": [328, "ParametersLong0|X_WDRC_ExpansionEnable[6]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[7]": [329, "ParametersLong0|X_WDRC_ExpansionEnable[7]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[8]": [330, "ParametersLong0|X_WDRC_ExpansionEnable[8]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[9]": [331, "ParametersLong0|X_WDRC_ExpansionEnable[9]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[10]": [332, "ParametersLong0|X_WDRC_ExpansionEnable[10]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[11]": [333, "ParametersLong0|X_WDRC_ExpansionEnable[11]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[12]": [334, "ParametersLong0|X_WDRC_ExpansionEnable[12]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[13]": [335, "ParametersLong0|X_WDRC_ExpansionEnable[13]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[14]": [336, "ParametersLong0|X_WDRC_ExpansionEnable[14]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionEnable[15]": [337, "ParametersLong0|X_WDRC_ExpansionEnable[15]", 0, 1, 1],
           "ParametersLong0|X_WDRC_ExpansionRatio[0]": [338, "ParametersLong0|X_WDRC_ExpansionRatio[0]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[1]": [339, "ParametersLong0|X_WDRC_ExpansionRatio[1]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[2]": [340, "ParametersLong0|X_WDRC_ExpansionRatio[2]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[3]": [341, "ParametersLong0|X_WDRC_ExpansionRatio[3]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[4]": [342, "ParametersLong0|X_WDRC_ExpansionRatio[4]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[5]": [343, "ParametersLong0|X_WDRC_ExpansionRatio[5]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[6]": [344, "ParametersLong0|X_WDRC_ExpansionRatio[6]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[7]": [345, "ParametersLong0|X_WDRC_ExpansionRatio[7]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[8]": [346, "ParametersLong0|X_WDRC_ExpansionRatio[8]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[9]": [347, "ParametersLong0|X_WDRC_ExpansionRatio[9]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[10]": [348, "ParametersLong0|X_WDRC_ExpansionRatio[10]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[11]": [349, "ParametersLong0|X_WDRC_ExpansionRatio[11]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[12]": [350, "ParametersLong0|X_WDRC_ExpansionRatio[12]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[13]": [351, "ParametersLong0|X_WDRC_ExpansionRatio[13]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[14]": [352, "ParametersLong0|X_WDRC_ExpansionRatio[14]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionRatio[15]": [353, "ParametersLong0|X_WDRC_ExpansionRatio[15]", 10, 30, 2],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[0]": [354, "ParametersLong0|X_WDRC_ExpansionReleaseTime[0]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[1]": [355, "ParametersLong0|X_WDRC_ExpansionReleaseTime[1]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[2]": [356, "ParametersLong0|X_WDRC_ExpansionReleaseTime[2]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[3]": [357, "ParametersLong0|X_WDRC_ExpansionReleaseTime[3]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[4]": [358, "ParametersLong0|X_WDRC_ExpansionReleaseTime[4]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[5]": [359, "ParametersLong0|X_WDRC_ExpansionReleaseTime[5]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[6]": [360, "ParametersLong0|X_WDRC_ExpansionReleaseTime[6]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[7]": [361, "ParametersLong0|X_WDRC_ExpansionReleaseTime[7]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[8]": [362, "ParametersLong0|X_WDRC_ExpansionReleaseTime[8]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[9]": [363, "ParametersLong0|X_WDRC_ExpansionReleaseTime[9]", 0,
                                                              13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[10]": [364, "ParametersLong0|X_WDRC_ExpansionReleaseTime[10]",
                                                               0, 13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[11]": [365, "ParametersLong0|X_WDRC_ExpansionReleaseTime[11]",
                                                               0, 13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[12]": [366, "ParametersLong0|X_WDRC_ExpansionReleaseTime[12]",
                                                               0, 13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[13]": [367, "ParametersLong0|X_WDRC_ExpansionReleaseTime[13]",
                                                               0, 13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[14]": [368, "ParametersLong0|X_WDRC_ExpansionReleaseTime[14]",
                                                               0, 13, 1],
           "ParametersLong0|X_WDRC_ExpansionReleaseTime[15]": [369, "ParametersLong0|X_WDRC_ExpansionReleaseTime[15]",
                                                               0, 13, 1],
           "ParametersLong0|X_WDRC_HighLevelGain[0]": [386, "ParametersLong0|X_WDRC_HighLevelGain[0]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[1]": [387, "ParametersLong0|X_WDRC_HighLevelGain[1]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[2]": [388, "ParametersLong0|X_WDRC_HighLevelGain[2]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[3]": [389, "ParametersLong0|X_WDRC_HighLevelGain[3]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[4]": [390, "ParametersLong0|X_WDRC_HighLevelGain[4]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[5]": [391, "ParametersLong0|X_WDRC_HighLevelGain[5]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[6]": [392, "ParametersLong0|X_WDRC_HighLevelGain[6]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[7]": [393, "ParametersLong0|X_WDRC_HighLevelGain[7]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[8]": [394, "ParametersLong0|X_WDRC_HighLevelGain[8]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[9]": [395, "ParametersLong0|X_WDRC_HighLevelGain[9]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[10]": [396, "ParametersLong0|X_WDRC_HighLevelGain[10]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[11]": [397, "ParametersLong0|X_WDRC_HighLevelGain[11]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[12]": [398, "ParametersLong0|X_WDRC_HighLevelGain[12]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[13]": [399, "ParametersLong0|X_WDRC_HighLevelGain[13]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[14]": [400, "ParametersLong0|X_WDRC_HighLevelGain[14]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelGain[15]": [401, "ParametersLong0|X_WDRC_HighLevelGain[15]", -30, 60, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[0]": [402, "ParametersLong0|X_WDRC_HighLevelThreshold[0]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[1]": [403, "ParametersLong0|X_WDRC_HighLevelThreshold[1]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[2]": [404, "ParametersLong0|X_WDRC_HighLevelThreshold[2]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[3]": [405, "ParametersLong0|X_WDRC_HighLevelThreshold[3]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[4]": [406, "ParametersLong0|X_WDRC_HighLevelThreshold[4]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[5]": [407, "ParametersLong0|X_WDRC_HighLevelThreshold[5]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[6]": [408, "ParametersLong0|X_WDRC_HighLevelThreshold[6]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[7]": [409, "ParametersLong0|X_WDRC_HighLevelThreshold[7]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[8]": [410, "ParametersLong0|X_WDRC_HighLevelThreshold[8]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[9]": [411, "ParametersLong0|X_WDRC_HighLevelThreshold[9]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[10]": [412, "ParametersLong0|X_WDRC_HighLevelThreshold[10]", 20,
                                                             110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[11]": [413, "ParametersLong0|X_WDRC_HighLevelThreshold[11]", 20,
                                                             110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[12]": [414, "ParametersLong0|X_WDRC_HighLevelThreshold[12]", 20,
                                                             110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[13]": [415, "ParametersLong0|X_WDRC_HighLevelThreshold[13]", 20,
                                                             110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[14]": [416, "ParametersLong0|X_WDRC_HighLevelThreshold[14]", 20,
                                                             110, 5],
           "ParametersLong0|X_WDRC_HighLevelThreshold[15]": [417, "ParametersLong0|X_WDRC_HighLevelThreshold[15]", 20,
                                                             110, 5],
           "ParametersLong0|X_WDRC_LimitAttackTime[0]": [498, "ParametersLong0|X_WDRC_LimitAttackTime[0]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[1]": [499, "ParametersLong0|X_WDRC_LimitAttackTime[1]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[2]": [500, "ParametersLong0|X_WDRC_LimitAttackTime[2]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[3]": [501, "ParametersLong0|X_WDRC_LimitAttackTime[3]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[4]": [502, "ParametersLong0|X_WDRC_LimitAttackTime[4]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[5]": [503, "ParametersLong0|X_WDRC_LimitAttackTime[5]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[6]": [504, "ParametersLong0|X_WDRC_LimitAttackTime[6]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[7]": [505, "ParametersLong0|X_WDRC_LimitAttackTime[7]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[8]": [506, "ParametersLong0|X_WDRC_LimitAttackTime[8]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[9]": [507, "ParametersLong0|X_WDRC_LimitAttackTime[9]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[10]": [508, "ParametersLong0|X_WDRC_LimitAttackTime[10]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[11]": [509, "ParametersLong0|X_WDRC_LimitAttackTime[11]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[12]": [510, "ParametersLong0|X_WDRC_LimitAttackTime[12]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[13]": [511, "ParametersLong0|X_WDRC_LimitAttackTime[13]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[14]": [512, "ParametersLong0|X_WDRC_LimitAttackTime[14]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitAttackTime[15]": [513, "ParametersLong0|X_WDRC_LimitAttackTime[15]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[0]": [514, "ParametersLong0|X_WDRC_LimitReleaseTime[0]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[1]": [515, "ParametersLong0|X_WDRC_LimitReleaseTime[1]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[2]": [516, "ParametersLong0|X_WDRC_LimitReleaseTime[2]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[3]": [517, "ParametersLong0|X_WDRC_LimitReleaseTime[3]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[4]": [518, "ParametersLong0|X_WDRC_LimitReleaseTime[4]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[5]": [519, "ParametersLong0|X_WDRC_LimitReleaseTime[5]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[6]": [520, "ParametersLong0|X_WDRC_LimitReleaseTime[6]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[7]": [521, "ParametersLong0|X_WDRC_LimitReleaseTime[7]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[8]": [522, "ParametersLong0|X_WDRC_LimitReleaseTime[8]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[9]": [523, "ParametersLong0|X_WDRC_LimitReleaseTime[9]", 0, 13, 1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[10]": [524, "ParametersLong0|X_WDRC_LimitReleaseTime[10]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[11]": [525, "ParametersLong0|X_WDRC_LimitReleaseTime[11]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[12]": [526, "ParametersLong0|X_WDRC_LimitReleaseTime[12]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[13]": [527, "ParametersLong0|X_WDRC_LimitReleaseTime[13]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[14]": [528, "ParametersLong0|X_WDRC_LimitReleaseTime[14]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_LimitReleaseTime[15]": [529, "ParametersLong0|X_WDRC_LimitReleaseTime[15]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_LowLevelGain[0]": [530, "ParametersLong0|X_WDRC_LowLevelGain[0]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[1]": [531, "ParametersLong0|X_WDRC_LowLevelGain[1]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[2]": [532, "ParametersLong0|X_WDRC_LowLevelGain[2]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[3]": [533, "ParametersLong0|X_WDRC_LowLevelGain[3]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[4]": [534, "ParametersLong0|X_WDRC_LowLevelGain[4]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[5]": [535, "ParametersLong0|X_WDRC_LowLevelGain[5]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[6]": [536, "ParametersLong0|X_WDRC_LowLevelGain[6]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[7]": [537, "ParametersLong0|X_WDRC_LowLevelGain[7]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[8]": [538, "ParametersLong0|X_WDRC_LowLevelGain[8]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[9]": [539, "ParametersLong0|X_WDRC_LowLevelGain[9]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[10]": [540, "ParametersLong0|X_WDRC_LowLevelGain[10]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[11]": [541, "ParametersLong0|X_WDRC_LowLevelGain[11]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[12]": [542, "ParametersLong0|X_WDRC_LowLevelGain[12]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[13]": [543, "ParametersLong0|X_WDRC_LowLevelGain[13]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[14]": [544, "ParametersLong0|X_WDRC_LowLevelGain[14]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelGain[15]": [545, "ParametersLong0|X_WDRC_LowLevelGain[15]", -30, 60, 5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[0]": [546, "ParametersLong0|X_WDRC_LowLevelThreshold[0]", 20, 110,
                                                           5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[1]": [547, "ParametersLong0|X_WDRC_LowLevelThreshold[1]", 20, 110,
                                                           5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[2]": [548, "ParametersLong0|X_WDRC_LowLevelThreshold[2]", 20, 110,
                                                           5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[3]": [549, "ParametersLong0|X_WDRC_LowLevelThreshold[3]", 20, 110,
                                                           5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[4]": [550, "ParametersLong0|X_WDRC_LowLevelThreshold[4]", 20, 110,
                                                           5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[5]": [551, "ParametersLong0|X_WDRC_LowLevelThreshold[5]", 20, 110,
                                                           5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[6]": [552, "ParametersLong0|X_WDRC_LowLevelThreshold[6]", 20, 110,
                                                           5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[7]": [553, "ParametersLong0|X_WDRC_LowLevelThreshold[7]", 20, 110,
                                                           5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[8]": [554, "ParametersLong0|X_WDRC_LowLevelThreshold[8]", 20, 110,
                                                           5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[9]": [555, "ParametersLong0|X_WDRC_LowLevelThreshold[9]", 20, 110,
                                                           5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[10]": [556, "ParametersLong0|X_WDRC_LowLevelThreshold[10]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[11]": [557, "ParametersLong0|X_WDRC_LowLevelThreshold[11]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[12]": [558, "ParametersLong0|X_WDRC_LowLevelThreshold[12]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[13]": [559, "ParametersLong0|X_WDRC_LowLevelThreshold[13]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[14]": [560, "ParametersLong0|X_WDRC_LowLevelThreshold[14]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_LowLevelThreshold[15]": [561, "ParametersLong0|X_WDRC_LowLevelThreshold[15]", 20,
                                                            110, 5],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[0]": [563, "ParametersLong0|X_WDRC_PrimaryAttackTime[0]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[1]": [564, "ParametersLong0|X_WDRC_PrimaryAttackTime[1]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[2]": [565, "ParametersLong0|X_WDRC_PrimaryAttackTime[2]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[3]": [566, "ParametersLong0|X_WDRC_PrimaryAttackTime[3]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[4]": [567, "ParametersLong0|X_WDRC_PrimaryAttackTime[4]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[5]": [568, "ParametersLong0|X_WDRC_PrimaryAttackTime[5]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[6]": [569, "ParametersLong0|X_WDRC_PrimaryAttackTime[6]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[7]": [570, "ParametersLong0|X_WDRC_PrimaryAttackTime[7]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[8]": [571, "ParametersLong0|X_WDRC_PrimaryAttackTime[8]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[9]": [572, "ParametersLong0|X_WDRC_PrimaryAttackTime[9]", 0, 13,
                                                           1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[10]": [573, "ParametersLong0|X_WDRC_PrimaryAttackTime[10]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[11]": [574, "ParametersLong0|X_WDRC_PrimaryAttackTime[11]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[12]": [575, "ParametersLong0|X_WDRC_PrimaryAttackTime[12]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[13]": [576, "ParametersLong0|X_WDRC_PrimaryAttackTime[13]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[14]": [577, "ParametersLong0|X_WDRC_PrimaryAttackTime[14]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryAttackTime[15]": [578, "ParametersLong0|X_WDRC_PrimaryAttackTime[15]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[0]": [579, "ParametersLong0|X_WDRC_PrimaryReleaseTime[0]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[1]": [580, "ParametersLong0|X_WDRC_PrimaryReleaseTime[1]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[2]": [581, "ParametersLong0|X_WDRC_PrimaryReleaseTime[2]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[3]": [582, "ParametersLong0|X_WDRC_PrimaryReleaseTime[3]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[4]": [583, "ParametersLong0|X_WDRC_PrimaryReleaseTime[4]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[5]": [584, "ParametersLong0|X_WDRC_PrimaryReleaseTime[5]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[6]": [585, "ParametersLong0|X_WDRC_PrimaryReleaseTime[6]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[7]": [586, "ParametersLong0|X_WDRC_PrimaryReleaseTime[7]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[8]": [587, "ParametersLong0|X_WDRC_PrimaryReleaseTime[8]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[9]": [588, "ParametersLong0|X_WDRC_PrimaryReleaseTime[9]", 0, 13,
                                                            1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[10]": [589, "ParametersLong0|X_WDRC_PrimaryReleaseTime[10]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[11]": [590, "ParametersLong0|X_WDRC_PrimaryReleaseTime[11]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[12]": [591, "ParametersLong0|X_WDRC_PrimaryReleaseTime[12]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[13]": [592, "ParametersLong0|X_WDRC_PrimaryReleaseTime[13]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[14]": [593, "ParametersLong0|X_WDRC_PrimaryReleaseTime[14]", 0,
                                                             13, 1],
           "ParametersLong0|X_WDRC_PrimaryReleaseTime[15]": [594, "ParametersLong0|X_WDRC_PrimaryReleaseTime[15]", 0,
                                                             13, 1]}
param_index = ["WDRC_LV", "X_WDRC", "X_HC", "X_EQ", "X_FBC", "X_FE", "X_NR", "X_SG", "OTHERS"]
save = True
# model_path = r"E:\python_ws\fitting_v1\e7111v2\trainer\saved_model\YPNet_2025_04_28_00_56_04"
this_file_dir = os.path.dirname(os.path.abspath(__file__))
model_path = os.path.join(this_file_dir, "..", "model")
model_name = "ypnet_v2_ultra"
# python_path = r"F:\app\miniconda\envs\huier\python"
chip_rg = {"e7111v2": 0, "audion6": 1, "audion16plus": 2, "ethos": 3, "e7111": 4, "e7160sl": 5, "audion16":6, "b300":7}
# chip_params_num = {0: 369, 1: 53, 2: 93, 3: 43, 4: 226, 5: 369, 6:93}
chip_params_num = {0: 243, 1: 53, 2: 93, 3: 43, 4: 226, 5: 243, 6:93}
# net_path = r"D:\python_ws\fitting_v1\networks\Ypnet.py"
